#local dev env only
services:
  app:
    build: .
    container_name: reservior-backend
    env_file:
      - .env
    command: npm start
    depends_on:
      - mongodb
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    volumes:
      - .:/app
    networks:
      - backend-network
  mongodb:
    image: mongo
    container_name: reservior-database
    env_file:
      - .env
    environment:
      - MONGODB_INITDB_ROOT_USERNAME=${MONGODB_INITDB_ROOT_USERNAME}
      - MONGODB_INITDB_ROOT_PASSWORD=${MONGODB_INITDB_ROOT_PASSWORD}
    ports:
      - ${MONGODB_INITDB_PORT}:${MONGODB_INITDB_PORT}
    volumes:
      - ./.database:/data/db
    networks:
      - backend-network

networks:
  backend-network:
    driver: bridge
